### ISSUE TITLE
Support for pull requests triggered workflows

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [ArcticLampyrid/action-wait-for-workflow#171]
It seems `ArcticLampyrid/action-wait-for-workflow@v1.0.4` does not wait for the configured workflow to succeed if the dependent workflow was triggered through `pull_request`. See for instance [this run](https://github.com/make-github-pseudonymous-again/recoll-api-rest/actions/runs/6627893910/job/18003815902) where no waiting happens. Compare to [this run](https://github.com/make-github-pseudonymous-again/recoll-api-rest/actions/runs/6627919432/job/18003904963) triggered through `push`.

**Comment by ArcticLampyrid** [comment]
A same workflow triggered by push for the aame commit may have finished. So there is no waiting.

Try to filter the actions by `event: pull_request` or `event: ${github.event_name}`

**Comment by make-github-pseudonymous-again** [comment]
> for the same commit 

I do not think that's possible given `push` is only enabled for the `main` branch, not for PR branches, and the current configuration filters by commit `sha`.

> event: ${github.event_name}

I will try that.

**Comment by make-github-pseudonymous-again** [comment]
> > event: ${github.event_name}
> 
> I will try that.

Does not seem to help: https://github.com/make-github-pseudonymous-again/recoll-api-rest/actions/runs/6657640420/job/18092764346?pr=2

**Comment by make-github-pseudonymous-again** [comment]
@ArcticLampyrid Experimenting this in another situation. Compare the following:

  - First run: https://github.com/infoderm/patients/actions/runs/8744824938/job/23998533109
  - Second run: https://github.com/infoderm/patients/actions/runs/8744824938/job/23998736184

The reason it fails on first run is because the referenced image has not been pushed yet to `ghcr.io`. On the second run it goes through because the image exists in the repo.

**Comment by ArcticLampyrid** [comment]
I've tweaked the logic and added more logs in v1.1.0.

Could you try v1.1.0 and see what the log outputs? Thanks.

**Comment by ArcticLampyrid** [comment]
Debug details:

I've noticed that the filter is set to infoderm/patients@5e782b2840caf7dee108bd501122e9e0717854ae (a temp merging commit used by action)
But the actions are triggered under infoderm/patients@d0d870eb05a55544300168a350fdedd6e66dbc5d ([Check here](https://api.github.com/repos/infoderm/patients/actions/workflows/ci:build:image.yml/runs?head_sha=d0d870eb05a55544300168a350fdedd6e66dbc5d))

**Comment by make-github-pseudonymous-again** [comment]
Thanks! Trying it here: https://github.com/infoderm/patients/pull/906.

**Comment by make-github-pseudonymous-again** [comment]
Seems to work on PRs! Let's see if it works on the merge queue too.

**Comment by make-github-pseudonymous-again** [comment]
Works too. I think you fixed it!
